data:
  train_query: "churn_modeling_workflow_one_train.sql"
  serving_query: "churn_modeling_workflow_one_serving.sql"
  monitor_query: "churn_modeling_workflow_one_monitor.sql"
  chunk_size: 40000
  levels:
    "0923_1737":
      context:
        tables:
          name: "0923_1737"
    "1023_2038":
      context:
        tables:
          name: "1023_2038"
    "1127_1528":
      context:
        tables:
          name: "1127_1528"
training:
  test_size: 0.3
  sample_weights: True
  model_1:
    target_accuracy: 0.7394
    scaler: "passthrough"
    model_name: "histgradientboosting"
    params:
      loss: "log_loss"
      learning_rate: 0.0090
      max_iter: 323
      max_leaf_nodes: 49
      max_depth: 3
      min_samples_leaf: 37
      l2_regularization: 0.0047
  model_2:
    target_accuracy: 0.6789
    scaler: "passthrough"
    model_name: "randomforest"
    params:
      n_estimators: 200
      max_depth: 10
      min_samples_leaf: 20
      max_features: "sqrt"
      class_weight: "balanced"
  model_3:
    target_accuracy: 0.7079
    scaler: "passthrough"
    model_name: "extratrees"
    params:
      n_estimators: 376
      max_depth: 25
      min_samples_split: 6
      min_samples_leaf: 2
      max_features: "sqrt"
serving:
  join_column:
    levels:
      "0923_1737":
        name: "MERCHANT_ID"
        type: "VARCHAR(16777216)"
      "1023_2038":
        name: "MERCHANT_ID"
        type: "VARCHAR(16777216)"
      "1127_1528":
        name: "MERCHANT_ID"
        type: "VARCHAR(16777216)"
  prediction_column:
    name: "PREDICTION"
    type: "INT"
  table_name: "ML_PREDICTION"
  output_path: "data/predictions"
monitor:
  null_rate:
    amber: 0.01
    red: 0.05
  feature_drift:
    green: 0.1
    amber: 0.3
  prediction_drift:
    green: 0.1
    amber: 0.2
  model_performance:
    green: 0.75
    amber: 0.60
  output_path: "data/monitoring"